spring:

  datasource:
    url: jdbc:mysql://localhost:33001/users_db
    username: root
    password: 1234
    #driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5Dialect

  #thymeleaf:
    #prefix: classpath:/templates/
    #suffix: .html

server:
  address: 127.0.0.1
  port: 8081


cxf:
  path: /services/

logging:
  level:
    sql: info
    org.springframework: info
    ru.netflex: debug