spring:

  datasource:
    url: jdbc:mysql://localhost:33003/comments_db
    username: root
    password: 1234
    #driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5Dialect


server:
  address: 127.0.0.1
  port: 8083


logging:
  level:
    sql: info
    org.springframework: info
    ru.netflex: debug