spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  thymeleaf:
    prefix: classpath:/templates

server:
  address: localhost
  port: 8801
  # servlet:
  #  context-path: /camunda

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    client:
      base-url: http://localhost:8801/engine-rest
    webapp:
      index-redirect-enabled: false
