
package ru.netflex.server.auth;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AuthorisationService", targetNamespace = "http://web.service.authserver.netflex.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorisationService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.netflex.server.auth.UserDto
     * @throws InvalidPasswordException_Exception
     * @throws UsernameNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorization", targetNamespace = "http://web.service.authserver.netflex.ru/", className = "ru.netflex.server.auth.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://web.service.authserver.netflex.ru/", className = "ru.netflex.server.auth.AuthorizationResponse")
    public UserDto authorization(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAuthorizationDto arg0)
        throws InvalidPasswordException_Exception, UsernameNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.netflex.server.auth.UserDto
     * @throws InvalidPasswordException_Exception
     * @throws InvalidUsernameException_Exception
     * @throws UserAlreadyExistsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registration", targetNamespace = "http://web.service.authserver.netflex.ru/", className = "ru.netflex.server.auth.Registration")
    @ResponseWrapper(localName = "registrationResponse", targetNamespace = "http://web.service.authserver.netflex.ru/", className = "ru.netflex.server.auth.RegistrationResponse")
    public UserDto registration(
        @WebParam(name = "arg0", targetNamespace = "")
        UserRegistrationDto arg0)
        throws InvalidPasswordException_Exception, InvalidUsernameException_Exception, UserAlreadyExistsException_Exception
    ;

}
