
package ru.netflex.server.auth;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InvalidUsernameException", targetNamespace = "http://web.service.authserver.netflex.ru/")
public class InvalidUsernameException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidUsernameException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidUsernameException_Exception(String message, InvalidUsernameException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InvalidUsernameException_Exception(String message, InvalidUsernameException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.netflex.server.auth.InvalidUsernameException
     */
    public InvalidUsernameException getFaultInfo() {
        return faultInfo;
    }

}
