
package ru.netflex.server.auth;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsernameNotFoundException", targetNamespace = "http://web.service.authserver.netflex.ru/")
public class UsernameNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsernameNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsernameNotFoundException_Exception(String message, UsernameNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsernameNotFoundException_Exception(String message, UsernameNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.netflex.server.auth.UsernameNotFoundException
     */
    public UsernameNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
