
package ru.netflex.server.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceAuthorization", targetNamespace = "http://auth.netflex.ru", wsdlLocation = "http://localhost:8081/services/auth?wsdl")
public class WebServiceAuthorization
    extends Service
{

    private static final URL WEBSERVICEAUTHORIZATION_WSDL_LOCATION;
    private static final WebServiceException WEBSERVICEAUTHORIZATION_EXCEPTION;
    private static final QName WEBSERVICEAUTHORIZATION_QNAME = new QName("http://auth.netflex.ru", "WebServiceAuthorization");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/services/auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEAUTHORIZATION_WSDL_LOCATION = url;
        WEBSERVICEAUTHORIZATION_EXCEPTION = e;
    }

    public WebServiceAuthorization() {
        super(__getWsdlLocation(), WEBSERVICEAUTHORIZATION_QNAME);
    }

    public WebServiceAuthorization(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEAUTHORIZATION_QNAME, features);
    }

    public WebServiceAuthorization(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEAUTHORIZATION_QNAME);
    }

    public WebServiceAuthorization(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEAUTHORIZATION_QNAME, features);
    }

    public WebServiceAuthorization(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceAuthorization(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthorisationService
     */
    @WebEndpoint(name = "AuthorizationPort")
    public AuthorisationService getAuthorizationPort() {
        return super.getPort(new QName("http://auth.netflex.ru", "AuthorizationPort"), AuthorisationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorisationService
     */
    @WebEndpoint(name = "AuthorizationPort")
    public AuthorisationService getAuthorizationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://auth.netflex.ru", "AuthorizationPort"), AuthorisationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEAUTHORIZATION_EXCEPTION!= null) {
            throw WEBSERVICEAUTHORIZATION_EXCEPTION;
        }
        return WEBSERVICEAUTHORIZATION_WSDL_LOCATION;
    }

}
