
package ru.netflex.server.movies;

import java.util.List;
import java.util.concurrent.Future;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.Response;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MovieService", targetNamespace = "http://service.moviesserver.netflex.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieService {


    /**
     * 
     * @param arg0
     * @return
     *     returns jakarta.xml.ws.Response<ru.netflex.server.movies.SaveMovieResponse>
     */
    @WebMethod(operationName = "saveMovie")
    @RequestWrapper(localName = "saveMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovie")
    @ResponseWrapper(localName = "saveMovieResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovieResponse")
    public Response<SaveMovieResponse> saveMovieAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "saveMovie")
    @RequestWrapper(localName = "saveMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovie")
    @ResponseWrapper(localName = "saveMovieResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovieResponse")
    public Future<?> saveMovieAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SaveMovieResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.netflex.server.movies.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovie")
    @ResponseWrapper(localName = "saveMovieResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.SaveMovieResponse")
    public Movie saveMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0);

    /**
     * 
     * @return
     *     returns jakarta.xml.ws.Response<ru.netflex.server.movies.GetAllMoviesResponse>
     */
    @WebMethod(operationName = "getAllMovies")
    @RequestWrapper(localName = "getAllMovies", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMovies")
    @ResponseWrapper(localName = "getAllMoviesResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMoviesResponse")
    public Response<GetAllMoviesResponse> getAllMoviesAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAllMovies")
    @RequestWrapper(localName = "getAllMovies", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMovies")
    @ResponseWrapper(localName = "getAllMoviesResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMoviesResponse")
    public Future<?> getAllMoviesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetAllMoviesResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<ru.netflex.server.movies.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMovies", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMovies")
    @ResponseWrapper(localName = "getAllMoviesResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetAllMoviesResponse")
    public List<Movie> getAllMovies();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.netflex.server.movies.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovieByTitle", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetMovieByTitle")
    @ResponseWrapper(localName = "getMovieByTitleResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetMovieByTitleResponse")
    public List<Movie> getMovieByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.netflex.server.movies.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovieById", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetMovieById")
    @ResponseWrapper(localName = "getMovieByIdResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.GetMovieByIdResponse")
    public Movie getMovieById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.netflex.server.movies.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.UpdateMovie")
    @ResponseWrapper(localName = "updateMovieResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.UpdateMovieResponse")
    public Movie updateMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.DeleteMovie")
    @ResponseWrapper(localName = "deleteMovieResponse", targetNamespace = "http://service.moviesserver.netflex.ru/", className = "ru.netflex.server.movies.DeleteMovieResponse")
    public void deleteMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
