
package ru.netflex.server.movies;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceMovie", targetNamespace = "http://service.moviesserver.netflex.ru/", wsdlLocation = "http://localhost:8082/services/movies?wsdl")
public class WebServiceMovie
    extends Service
{

    private static final URL WEBSERVICEMOVIE_WSDL_LOCATION;
    private static final WebServiceException WEBSERVICEMOVIE_EXCEPTION;
    private static final QName WEBSERVICEMOVIE_QNAME = new QName("http://service.moviesserver.netflex.ru/", "WebServiceMovie");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/services/movies?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEMOVIE_WSDL_LOCATION = url;
        WEBSERVICEMOVIE_EXCEPTION = e;
    }

    public WebServiceMovie() {
        super(__getWsdlLocation(), WEBSERVICEMOVIE_QNAME);
    }

    public WebServiceMovie(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEMOVIE_QNAME, features);
    }

    public WebServiceMovie(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEMOVIE_QNAME);
    }

    public WebServiceMovie(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEMOVIE_QNAME, features);
    }

    public WebServiceMovie(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceMovie(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MovieService
     */
    @WebEndpoint(name = "MoviePort")
    public MovieService getMoviePort() {
        return super.getPort(new QName("http://service.moviesserver.netflex.ru/", "MoviePort"), MovieService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieService
     */
    @WebEndpoint(name = "MoviePort")
    public MovieService getMoviePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.moviesserver.netflex.ru/", "MoviePort"), MovieService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEMOVIE_EXCEPTION!= null) {
            throw WEBSERVICEMOVIE_EXCEPTION;
        }
        return WEBSERVICEMOVIE_WSDL_LOCATION;
    }

}
